defmodule Batata.Godot.Adapter do
  @moduledoc """
  Deterministic source generation for the minimal raw GDExtension adapter.

  This adapter establishes only the load/initialize/deinitialize boundary.
  ClassDB registration and method trampolines are deliberately absent until
  their ownership and callback semantics are implemented.
  """

  alias Batata.Godot.BindingPlan

  @initialization_levels %{core: 0, servers: 1, scene: 2, editor: 3}

  @doc "Renders the Zig source for a validated binding plan."
  @spec zig_source(BindingPlan.t()) :: String.t()
  def zig_source(%BindingPlan{} = plan) do
    level = Map.fetch!(@initialization_levels, plan.initialization_level)

    """
    // Generated by Batata.Godot from binding plan #{BindingPlan.digest(plan)}.
    // Raw ABI surface: Godot 4.6.2 gdextension_interface.json.
    const GDExtensionBool = u8;
    const GDExtensionInitializationLevel = c_int;
    const GDExtensionInterfaceFunctionPtr = ?*const fn () callconv(.c) void;
    const GDExtensionInterfaceGetProcAddress = ?*const fn ([*:0]const u8) callconv(.c) GDExtensionInterfaceFunctionPtr;
    const GDExtensionClassLibraryPtr = ?*anyopaque;
    const GDExtensionInitializationCallback = *const fn (?*anyopaque, GDExtensionInitializationLevel) callconv(.c) void;

    const GDExtensionInitialization = extern struct {
        minimum_initialization_level: GDExtensionInitializationLevel,
        userdata: ?*anyopaque,
        initialize: GDExtensionInitializationCallback,
        deinitialize: GDExtensionInitializationCallback,
    };

    fn initialize(userdata: ?*anyopaque, level: GDExtensionInitializationLevel) callconv(.c) void {
        _ = userdata;
        _ = level;
    }

    fn deinitialize(userdata: ?*anyopaque, level: GDExtensionInitializationLevel) callconv(.c) void {
        _ = userdata;
        _ = level;
    }

    fn extensionEntry(
        get_proc_address: GDExtensionInterfaceGetProcAddress,
        library: GDExtensionClassLibraryPtr,
        initialization: *GDExtensionInitialization,
    ) callconv(.c) GDExtensionBool {
        if (get_proc_address == null or library == null) return 0;

        initialization.* = .{
            .minimum_initialization_level = #{level},
            .userdata = null,
            .initialize = &initialize,
            .deinitialize = &deinitialize,
        };

        return 1;
    }

    comptime {
        @export(&extensionEntry, .{ .name = "#{plan.entry_symbol}" });
    }
    """
  end

  @doc "Renders the `.gdextension` resource for the initial macOS arm64 target."
  @spec gdextension_source(BindingPlan.t(), String.t()) :: String.t()
  def gdextension_source(%BindingPlan{} = plan, library_name) when is_binary(library_name) do
    """
    [configuration]

    entry_symbol = "#{plan.entry_symbol}"
    compatibility_minimum = "#{plan.compatibility_minimum}"
    reloadable = #{plan.reloadable}

    [libraries]

    macos.debug.arm64 = "res://bin/#{library_name}"
    """
  end
end
